/**
 * pdf.service.js
 * -----------------------------------------------------------------
 * Builds a polished, branded PDF summary of a trip's itinerary using
 * pdfkit — vector shapes plus the standard built-in Helvetica fonts
 * only, so it needs no extra font files or network access to render
 * correctly on any machine. Used by GET /api/trips/:id/export-pdf.
 * -----------------------------------------------------------------
 */
const PDFDocument = require('pdfkit');
const axios = require('axios');

const COLORS = {
  brand: '#0d9488',
  brandDark: '#0f766e',
  brandSoft: '#ccfbf1',
  ink: '#1e293b',
  muted: '#64748b',
  border: '#e2e8f0',
  bgSoft: '#f8fafc',
  white: '#ffffff',
};

const CATEGORY_COLORS = ['#0d9488', '#2563eb', '#d97706', '#db2777', '#7c3aed', '#059669', '#dc2626'];

const PAGE_MARGIN = 50;

function toNum(v) {
  if (v == null) return 0;
  return typeof v.toNumber === 'function' ? v.toNumber() : Number(v);
}

/**
 * The Indian Rupee sign (₹) is outside the standard PDF base-14 fonts'
 * character set, so it can render as a blank box. "Rs." is guaranteed
 * to render correctly with the built-in Helvetica font on every machine.
 */
function money(currency, amount) {
  const prefix = currency && currency !== 'INR' ? `${currency} ` : 'Rs. ';
  return `${prefix}${toNum(amount).toLocaleString('en-IN')}`;
}

function formatShortDate(d) {
  return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' });
}

function categoryColor(category) {
  if (!category) return CATEGORY_COLORS[0];
  const seed = category.split('').reduce((acc, ch) => acc + ch.charCodeAt(0), 0);
  return CATEGORY_COLORS[seed % CATEGORY_COLORS.length];
}

/**
 * Downloads the destination's cover photo for the PDF's first-page hero
 * band. pdfkit can only embed JPEG/PNG image data, so anything else (or
 * any network failure, timeout, 404, etc.) is treated as "no photo" —
 * the PDF then falls back to the plain brand-colored band instead of
 * failing the whole export.
 */
async function fetchCoverImage(url) {
  if (!url) return null;
  try {
    const response = await axios.get(url, { responseType: 'arraybuffer', timeout: 8000 });
    const contentType = String(response.headers['content-type'] || '').toLowerCase();
    if (!contentType.includes('jpeg') && !contentType.includes('jpg') && !contentType.includes('png')) {
      return null;
    }
    return Buffer.from(response.data);
  } catch (err) {
    return null;
  }
}

/** Adds a new page if the given block wouldn't fit before the footer. */
function ensureSpace(doc, height) {
  const bottomLimit = doc.page.height - doc.page.margins.bottom - 25;
  if (doc.y + height > bottomLimit) {
    doc.addPage();
  }
}

function drawStatCard(doc, x, y, w, label, value) {
  const h = 46;
  doc.roundedRect(x, y, w, h, 6).fillAndStroke(COLORS.bgSoft, COLORS.border);
  doc.rect(x, y, 4, h).fill(COLORS.brand);
  doc.fontSize(7.5).font('Helvetica-Bold').fillColor(COLORS.muted)
    .text(label.toUpperCase(), x + 12, y + 9, { width: w - 20, characterSpacing: 0.5 });
  doc.fontSize(10.5).font('Helvetica-Bold').fillColor(COLORS.ink)
    .text(value, x + 12, y + 23, { width: w - 20 });
}

function drawFooter(doc, pageNumber, pageCount) {
  const y = doc.page.height - 40;
  doc.moveTo(PAGE_MARGIN, y).lineTo(doc.page.width - PAGE_MARGIN, y).lineWidth(0.5).strokeColor(COLORS.border).stroke();
  doc.fontSize(8).font('Helvetica').fillColor(COLORS.muted)
    .text('Generated by IntelliTrip — AI-Driven Travel Planning Platform', PAGE_MARGIN, y + 8, { width: 320 });
  doc.fontSize(8).font('Helvetica').fillColor(COLORS.muted)
    .text(`Page ${pageNumber} of ${pageCount}`, doc.page.width - PAGE_MARGIN - 100, y + 8, { width: 100, align: 'right' });
}

/** Streams a PDF for the given trip directly to the HTTP response. */
async function streamTripPdf(trip, res) {
  const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN, bufferPages: true });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${trip.title.replace(/[^a-z0-9]/gi, '_')}.pdf"`);
  doc.pipe(res);

  const pageWidth = doc.page.width;
  const contentWidth = pageWidth - PAGE_MARGIN * 2;
  const pageRight = PAGE_MARGIN + contentWidth;

  const coverImage = await fetchCoverImage(trip.destination?.imageUrl);

  // ---- Header band / cover photo -----------------------------------------
  // With a photo: the image fills the band edge-to-edge (cropped like
  // CSS "object-fit: cover") with a dark gradient over the bottom so the
  // white title text stays readable. Without one (no image URL, download
  // failed, or an unsupported format): a flat brand-colored band, same as
  // before this feature was added.
  const bandHeight = coverImage ? 200 : 118;

  if (coverImage) {
    try {
      doc.save();
      doc.rect(0, 0, pageWidth, bandHeight).clip();
      doc.image(coverImage, 0, 0, { cover: [pageWidth, bandHeight], align: 'center', valign: 'center' });
      doc.restore();
    } catch (err) {
      doc.rect(0, 0, pageWidth, bandHeight).fill(COLORS.brandDark);
    }
    const gradient = doc.linearGradient(0, 0, 0, bandHeight);
    gradient.stop(0, COLORS.brandDark, 0).stop(0.55, COLORS.brandDark, 0.35).stop(1, COLORS.brandDark, 0.92);
    doc.rect(0, 0, pageWidth, bandHeight).fill(gradient);
  } else {
    doc.rect(0, 0, pageWidth, bandHeight).fill(COLORS.brandDark);
  }

  doc.fontSize(9).font('Helvetica-Bold').fillColor(COLORS.brandSoft)
    .text('INTELLITRIP', PAGE_MARGIN, bandHeight - 88, { characterSpacing: 1.5 });
  doc.fontSize(23).font('Helvetica-Bold').fillColor(COLORS.white)
    .text(trip.title, PAGE_MARGIN, bandHeight - 72, { width: contentWidth });
  const destinationName = trip.destination ? trip.destination.name : 'N/A';
  doc.fontSize(10.5).font('Helvetica').fillColor(COLORS.brandSoft)
    .text(
      `${destinationName}   •   ${new Date(trip.startDate).toDateString()} - ${new Date(trip.endDate).toDateString()}`,
      PAGE_MARGIN,
      bandHeight - 38,
      { width: contentWidth }
    );

  doc.y = bandHeight + 24;

  // ---- Stat row -----------------------------------------------------------
  const gap = 12;
  const cardW = (contentWidth - gap * 3) / 4;
  const statY = doc.y;
  const budgetValue = trip.estimatedBudget ?? trip.budget;
  drawStatCard(doc, PAGE_MARGIN, statY, cardW, 'Dates', `${formatShortDate(trip.startDate)} - ${formatShortDate(trip.endDate)}`);
  drawStatCard(doc, PAGE_MARGIN + (cardW + gap), statY, cardW, 'Travellers', String(trip.travellers));
  drawStatCard(doc, PAGE_MARGIN + (cardW + gap) * 2, statY, cardW, 'Budget', budgetValue ? money(trip.currency, budgetValue) : 'N/A');
  drawStatCard(doc, PAGE_MARGIN + (cardW + gap) * 3, statY, cardW, 'Trip type', trip.tripType || 'Leisure');
  doc.y = statY + 46 + 24;

  // ---- AI summary ---------------------------------------------------------
  if (trip.aiSummary) {
    doc.font('Helvetica-Oblique').fontSize(10.5);
    const summaryHeight = doc.heightOfString(trip.aiSummary, { width: contentWidth - 36 }) + 24;
    ensureSpace(doc, summaryHeight);
    const boxY = doc.y;
    doc.roundedRect(PAGE_MARGIN, boxY, contentWidth, summaryHeight, 6).fill(COLORS.brandSoft);
    doc.rect(PAGE_MARGIN, boxY, 4, summaryHeight).fill(COLORS.brand);
    doc.fillColor(COLORS.brandDark).font('Helvetica-Oblique').fontSize(10.5)
      .text(trip.aiSummary, PAGE_MARGIN + 18, boxY + 12, { width: contentWidth - 36 });
    doc.y = boxY + summaryHeight + 24;
  }

  // ---- Days ----------------------------------------------------------------
  let grandTotal = 0;

  trip.days.forEach((day) => {
    ensureSpace(doc, 50);
    const dayY = doc.y;
    doc.circle(PAGE_MARGIN + 12, dayY + 12, 14).fill(COLORS.brand);
    doc.fontSize(11).font('Helvetica-Bold').fillColor(COLORS.white)
      .text(String(day.dayNumber), PAGE_MARGIN, dayY + 6, { width: 24, align: 'center' });
    doc.fontSize(14).font('Helvetica-Bold').fillColor(COLORS.ink)
      .text(day.title ? day.title : `Day ${day.dayNumber}`, PAGE_MARGIN + 34, dayY + 3, { width: contentWidth - 34 });
    doc.moveTo(PAGE_MARGIN, dayY + 34).lineTo(pageRight, dayY + 34).lineWidth(1).strokeColor(COLORS.border).stroke();
    doc.y = dayY + 46;

    (day.items || []).forEach((item) => {
      grandTotal += toNum(item.estimatedCost);

      const innerLeft = PAGE_MARGIN + 16;
      const innerRight = pageRight - 12;

      let pillW = 0;
      if (item.startTime) {
        doc.font('Helvetica-Bold').fontSize(8);
        pillW = doc.widthOfString(item.startTime) + 14;
      }
      const nameX = item.startTime ? innerLeft + pillW + 10 : innerLeft;
      const nameWidth = innerRight - nameX;

      doc.font('Helvetica-Bold').fontSize(11);
      const nameHeight = doc.heightOfString(item.name || '', { width: nameWidth });
      const headerRowHeight = Math.max(item.startTime ? 15 : 0, nameHeight);

      const descText = item.description || '';
      doc.font('Helvetica').fontSize(9);
      const descHeight = descText ? doc.heightOfString(descText, { width: innerRight - innerLeft }) : 0;

      const meta = [
        item.location || null,
        item.durationMinutes != null ? `${item.durationMinutes} min` : null,
        money(trip.currency, item.estimatedCost),
        item.category || null,
      ].filter(Boolean).join('   •   ');
      doc.font('Helvetica').fontSize(8.5);
      const metaHeight = doc.heightOfString(meta, { width: innerRight - innerLeft });

      const paddingTop = 10;
      const gapAfterHeader = 8;
      const gapAfterDesc = descText ? 8 : 0;
      const paddingBottom = 10;
      const cardHeight = paddingTop + headerRowHeight + gapAfterHeader + descHeight + gapAfterDesc + metaHeight + paddingBottom;

      ensureSpace(doc, cardHeight + 12);
      const cardY = doc.y;
      doc.roundedRect(PAGE_MARGIN, cardY, contentWidth, cardHeight, 5).fillAndStroke(COLORS.bgSoft, COLORS.border);
      doc.rect(PAGE_MARGIN, cardY, 4, cardHeight).fill(categoryColor(item.category));

      if (item.startTime) {
        doc.roundedRect(innerLeft, cardY + paddingTop, pillW, 15, 7).fill(COLORS.brand);
        doc.fontSize(8).font('Helvetica-Bold').fillColor(COLORS.white)
          .text(item.startTime, innerLeft, cardY + paddingTop + 4, { width: pillW, align: 'center' });
      }
      doc.fontSize(11).font('Helvetica-Bold').fillColor(COLORS.ink)
        .text(item.name || '', nameX, cardY + paddingTop, { width: nameWidth });

      let cursorY = cardY + paddingTop + headerRowHeight + gapAfterHeader;
      if (descText) {
        doc.fontSize(9).font('Helvetica').fillColor(COLORS.muted)
          .text(descText, innerLeft, cursorY, { width: innerRight - innerLeft });
        cursorY += descHeight + gapAfterDesc;
      }
      doc.fontSize(8.5).font('Helvetica').fillColor(COLORS.muted)
        .text(meta, innerLeft, cursorY, { width: innerRight - innerLeft });

      doc.y = cardY + cardHeight + 10;
    });
  });

  // ---- Total cost summary ---------------------------------------------------
  ensureSpace(doc, 60);
  const totalY = doc.y + 4;
  doc.roundedRect(PAGE_MARGIN, totalY, contentWidth, 44, 6).fill(COLORS.brandDark);
  doc.fontSize(9).font('Helvetica-Bold').fillColor(COLORS.brandSoft)
    .text('ESTIMATED TOTAL COST (ALL ACTIVITIES)', PAGE_MARGIN + 16, totalY + 16, { characterSpacing: 0.3, width: contentWidth * 0.55 });
  doc.fontSize(16).font('Helvetica-Bold').fillColor(COLORS.white)
    .text(money(trip.currency, grandTotal), PAGE_MARGIN, totalY + 12, { width: contentWidth - 16, align: 'right' });
  doc.y = totalY + 44 + 10;

  // ---- Footer (page numbers need the full page count, so this runs last) --
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    drawFooter(doc, i - range.start + 1, range.count);
  }

  doc.end();
}

module.exports = { streamTripPdf };
